Migrate ui pattern samples
enactjs/samples pull request #101
Opened 2021-05-27 01:25 UTC by juwonjeong

Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)

### Checklist
* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Put common pattern samples into ui folder 

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Update dependencies
Remove theme decorator from ui pattern samples

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
PLAT-142864
### Comments

2021-05-28 00:45 UTC, juwonjeong commented on ui/pattern-layout/src/App/App.js
> +import {ActivityPanels} from '@enact/moonstone/Panels';
I couldn't remove ActivityPanel as it was related to page index.

2021-06-03 00:58 UTC, MikyungKim commented on ui/pattern-analytics-webostv/src/views/MainPanel.js
> -			<IconButton aria-label="ZOOM">livezoom</IconButton>
I think we should keep this since it's used in the configure file. 🤔

2021-06-03 01:01 UTC, MikyungKim commented on ui/pattern-analytics-webostv/src/views/MainPanel.js
> +		<div {...props} style={{position: 'absolute', inset: '0px 18px 24px', overflow: 'hidden'}}>
Please use className instead of style.
Also, please don't use inset, let's use `.position` mixin instead.
For example,
```
@import '~@enact/ui/styles/mixins.less';

.main {
	position: absolute;
	.position(0);
	background-color: white;
	padding: 48px;
}
```
background-color added since on TV, the background looks black color so I can't see the text.
Please apply this to `pattern-analytics` sample too.

2021-06-17 00:24 UTC, juwonjeong commented on ui/pattern-analytics-webostv/src/views/MainPanel.js
> -			<IconButton aria-label="ZOOM">livezoom</IconButton>
I restored those buttons.

2021-06-17 00:24 UTC, juwonjeong commented on ui/pattern-analytics-webostv/src/views/MainPanel.js
> +		<div {...props} style={{position: 'absolute', inset: '0px 18px 24px', overflow: 'hidden'}}>
It's applied.

2021-06-18 08:05 UTC, MikyungKim commented on ui/pattern-analytics/src/views/MainPanel.module.less
> +    .position(48px);
Why 48px used instead of 0?

2021-06-18 08:08 UTC, MikyungKim commented on ui/pattern-layout/src/App/App.js
> +import {ActivityPanels} from '@enact/moonstone/Panels';
🤔 If not, then I think we should move this sample to theme folders each.

2021-06-21 01:44 UTC, MikyungKim commented on ui/pattern-list-details-redux/src/components/Nav/Nav.js
>  		<React.Fragment>
Would you please import `Fragment` from `react` instead of importing React?

2021-06-21 02:06 UTC, MikyungKim requested changes
We've got below lint warnings when we run `enact lint . --strict` under `ui` folder.
Please fix them.

```

/home/mikyung27.kim/github/samples/ui/pattern-layout/src/views/Details.js
  47:10  warning  'spotlightId' is missing in props validation   enact/prop-types
  48:10  warning  'hideChildren' is missing in props validation  enact/prop-types

/home/mikyung27.kim/github/samples/ui/pattern-layout/src/views/FavoritesList.js
  48:10  warning  'spotlightId' is missing in props validation   enact/prop-types
  49:10  warning  'hideChildren' is missing in props validation  enact/prop-types

/home/mikyung27.kim/github/samples/ui/pattern-layout/src/views/MainPanel.js
  70:10  warning  'spotlightId' is missing in props validation   enact/prop-types
  71:10  warning  'hideChildren' is missing in props validation  enact/prop-types

/home/mikyung27.kim/github/samples/ui/pattern-list-details/src/components/tests/Content-specs.js
  2:8  warning  'React' is defined but never used  no-unused-vars

/home/mikyung27.kim/github/samples/ui/pattern-list-details/src/components/tests/Nav-specs.js
  2:8  warning  'React' is defined but never used  no-unused-vars

/home/mikyung27.kim/github/samples/ui/pattern-list-details/src/components/tests/SideBar-specs.js
  2:8  warning  'React' is defined but never used  no-unused-vars

/home/mikyung27.kim/github/samples/ui/pattern-ls2request/src/App/App.js
  15:3   warning  Prop types declarations should be sorted alphabetically  react/sort-prop-types
  44:3   warning  Missing semicolon                                        babel/semi
  48:65  warning  Unexpected whitespace before semicolon                   semi-spacing
  55:3   warning  Missing semicolon                                        babel/semi

✖ 13 problems (0 errors, 13 warnings)
  0 errors and 3 warnings potentially fixable with the `--fix` option.
```

2021-06-22 03:00 UTC, DavidUM commented
How about adopt lint plugin in package.json at root directory?
You can reduce time and effort.

2021-06-22 04:32 UTC, MikyungKim commented
@DavidUM Hey~~ How have you been?
Thank you! We are planning to fix it right in near future. :)

2021-06-22 07:31 UTC, juwonjeong commented on ui/pattern-analytics/src/views/MainPanel.module.less
> +    .position(48px);
It's fixed.

2021-06-22 07:31 UTC, juwonjeong commented on ui/pattern-list-details-redux/src/components/Nav/Nav.js
>  		<React.Fragment>
It's fixed.

2021-06-22 07:31 UTC, juwonjeong commented on ui/pattern-layout/src/App/App.js
> +import {ActivityPanels} from '@enact/moonstone/Panels';
It's moved to each theme folders.

2021-06-23 01:40 UTC, MikyungKim commented on ui/pattern-list-details/src/views/MainView.module.less
> +    align-items: center;
Please check the indentation.

2021-06-23 02:06 UTC, MikyungKim approved these changes
Great Job! 👏 
I have 3 more comments and then it'll be good to merge.

1. Please run enact lint . -s to moonstone, sandstone, and agate folder and fix them as you did in ui folder.

2. Please see sandstone/pattern-layout views. The bottom line of the layout border is overflowed. Would you please fix them? And also, if possible, please re-position the buttons for "Layout Borders" and "Flip Orientation" like moonstone's.
![image](https://user-images.githubusercontent.com/5037429/123023259-0d259a00-d412-11eb-90a9-acb8802770fb.png)

3. I found there is no selected status to the Buttons in Favorites List view like below in sandstone and agate. Please see what you can do.
![image](https://user-images.githubusercontent.com/5037429/123023329-29c1d200-d412-11eb-887e-50aefe23a384.png)

Except for them, LGTM.

2021-06-23 06:31 UTC, juwonjeong commented on ui/pattern-list-details/src/views/MainView.module.less
> +    align-items: center;
It's fixed.

2021-06-24 00:05 UTC, MikyungKim approved these changes
:lgtm:

2021-06-24 05:34 UTC, seunghoh approved these changes

2021-06-24 05:35 UTC, merged