PLAT-142871: Migrate sandstone pattern samples
enactjs/samples pull request #102
Opened 2021-06-08 01:47 UTC by juwonjeong

Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)

### Checklist
* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Put sandstone related pattern samples into sandstone folder

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Update dependencies 
Apply sandstone theme 

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
PLAT-142871

### Comments

2021-06-08 04:53 UTC, jeonghee27 commented on sandstone/pattern-single-panel-redux/src/views/MainPanel.js
> +			<Header casing="preserve" subtitle="Choose your profile picture" title="Profile Photo Redux"  type="compact" />
```suggestion
			<Header casing="preserve" subtitle="Choose your profile picture" title="Profile Photo Redux" type="compact" />
```

2021-06-11 07:26 UTC, jeonghee27 commented on sandstone/pattern-video-player/src/App/App.js
> +						<Button
Sorry, I didn't reload page after changing the view size.

2021-06-11 08:15 UTC, juwonjeong commented on sandstone/pattern-single-panel-redux/src/views/MainPanel.js
> +			<Header casing="preserve" subtitle="Choose your profile picture" title="Profile Photo Redux"  type="compact" />
It's fixed.

2021-06-11 08:15 UTC, juwonjeong commented on sandstone/pattern-virtualgridlist-api/src/components/GalleryPanelHeader/GalleryPanelHeader.js
> +				icon = showOverlay ? 'refresh' : 'check';
It's fixed.

2021-06-11 08:19 UTC, juwonjeong commented
@jeonghee27 I also changed CheckboxItem to Button in pattern-virtualgridlist-api Sidebar component.
![image](https://user-images.githubusercontent.com/77044692/121654935-30c71700-cad9-11eb-9674-9e975971a4a3.png)

2021-06-14 06:17 UTC, jeonghee27 approved these changes
LGTM

2021-06-21 01:54 UTC, 0x64 requested changes

2021-06-21 01:54 UTC, 0x64 commented on sandstone/pattern-virtualgridlist-api/src/components/ImageItem/ImageItem.js
> +const ImageItems = kind({
I understand that this is named `ImageItems` to avoid conflict with the imported `ImageItem` component, but it does not render items but a single item. It would be better to rename it.

2021-06-21 01:54 UTC, 0x64 commented on sandstone/pattern-locale-switching/src/components/LocaleSwitch/package.json
> +}
No new line at the end of this line.

2021-06-21 01:54 UTC, 0x64 commented on sandstone/pattern-locale-switching/src/components/LocaleSwitch/LocaleSwitch.js
> +				<p>This locale {this.props.rtl ? 'is' : 'isn\'t'} RTL</p>
'rtl' is missing in props validation

2021-06-21 01:54 UTC, 0x64 commented on sandstone/pattern-single-panel/src/components/tests/ProfilePhotoPicker-specs.js
> +import React from 'react';
We don't need to import 'React'.

2021-06-21 01:54 UTC, 0x64 commented on sandstone/pattern-single-panel/src/components/tests/SaveButton-specs.js
> +import React from 'react';
We don't need to import 'React'.

2021-06-21 01:54 UTC, 0x64 commented on sandstone/pattern-video-player/src/App/App.js
> +						actionGuideLabel="Press Down Button">
Please make <MediaControls> into a single line or move the closing bracket to the next line.

2021-06-21 05:12 UTC, juwonjeong commented on sandstone/pattern-virtualgridlist-api/src/components/ImageItem/ImageItem.js
> +const ImageItems = kind({
It's renamed to `GalleryItem`.

2021-06-21 05:13 UTC, juwonjeong commented on sandstone/pattern-locale-switching/src/components/LocaleSwitch/package.json
> +}
It's added.

2021-06-21 05:13 UTC, juwonjeong commented on sandstone/pattern-locale-switching/src/components/LocaleSwitch/LocaleSwitch.js
> +				<p>This locale {this.props.rtl ? 'is' : 'isn\'t'} RTL</p>
It's added.

2021-06-21 05:13 UTC, juwonjeong commented on sandstone/pattern-single-panel/src/components/tests/ProfilePhotoPicker-specs.js
> +import React from 'react';
It's removed.

2021-06-21 05:13 UTC, juwonjeong commented on sandstone/pattern-single-panel/src/components/tests/SaveButton-specs.js
> +import React from 'react';
It's removed.

2021-06-21 05:13 UTC, juwonjeong commented on sandstone/pattern-video-player/src/App/App.js
> +						actionGuideLabel="Press Down Button">
It's fixed.

2021-06-21 06:35 UTC, 0x64 approved these changes

2021-06-21 06:35 UTC, merged