WRN-6829: Add Camera Sample
enactjs/samples pull request #148
Opened 2022-02-11 08:03 UTC by juwonjeong

Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)

### Checklist
* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Add pattern-camera sample

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRN-6829

### Comments

2022-02-22 06:19 UTC, seunghoh requested changes
Besides the inline comment, let's 
1. change the repo name to pattern-ls2request-camera so that developer can understand this is luna service sample not, web media standard sample
2. Please add a comment at the top of the app.js file like "To use camera API, you need to XXXX for webOS permissions."

2022-02-24 01:59 UTC, juwonjeong commented on sandstone/pattern-camera/src/components/CameraView.js
> +		videoRef.current.load();
It's fixed

2022-02-24 04:22 UTC, seunghoh commented on sandstone/pattern-ls2request-camera/src/components/CameraView.js
> +	cameraOption = escape(JSON.stringify({
I am not asking to replace now but please keep in mind that escape() will be deprecated. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape
FYI, :)

2022-02-24 04:58 UTC, seunghoh approved these changes
💯

2022-02-24 05:01 UTC, merged