WRN-19202: Added Sample for React 18 Features
enactjs/samples pull request #158
Opened 2022-03-22 09:11 UTC by daniel-stoian-lgp

### Checklist

* [ ] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Added Sample for React 18 Features

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRN-19202

### Comments

Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com

2022-03-22 09:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/enactjs/samples?pullRequest=158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/enactjs/samples?pullRequest=158) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: daniel-stoian-lgp<br/>:white_check_mark: alexandrumorariu<br/>:white_check_mark: stanca-pop-lgp<br/>:x: vladut-clapou-lgp<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/enactjs/samples?pullRequest=158) it.</sub>

2022-03-24 06:06 UTC, seunghoh requested changes

2022-03-24 08:01 UTC, daniel-stoian-lgp commented on sandstone/pattern-react18-new/src/views/Suspense/SkeletonPage.js
> +for (let i = 0; i < 12; i++) {
no, it's not needed. I will remove it

2022-03-24 09:09 UTC, daniel-stoian-lgp commented on sandstone/pattern-react18-new/src/index.js
> +import {createRoot} from 'react-dom';
it seems that it has changed recently. announcement on GH about this change was made on March 1st. Thank you for the warning

2022-03-25 07:09 UTC, seunghoh approved these changes
LGTM!

2022-04-15 05:48 UTC, hong6316 commented
For updating sandstone/ui samples` whole changes related react18, merge this PR in [feature/WRO-2831](https://github.com/enactjs/samples/tree/feature/WRO-2831) branch

2022-04-15 05:49 UTC, hong6316 approved these changes
LGTM

2022-04-15 05:49 UTC, hong6316 commented on sandstone/pattern-react18-new/package.json
> +  "dependencies": {
Done

2022-04-15 05:50 UTC, merged