WRO-11485: Update package dependencies to fix security vulnerabilities - Samples
enactjs/samples pull request #184
Opened 2022-10-19 09:00 UTC by andreitirlalge

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Updated dependencies for Moonstone, Sandstone, Agate and UI.
Migrated react-router-dom from version from 5.2.0 to 6.4.2.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Dependencies now use the latest version.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRO-11485

### Comments
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com

2022-10-19 09:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/enactjs/samples?pullRequest=184) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/enactjs/samples?pullRequest=184) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/enactjs/samples?pullRequest=184) it.</sub>

2022-10-25 08:33 UTC, hong6316 reviewed
Could you consider `"readdirp": "^3.6.0"` in the root directory? like WRO-460?(Please make a new ticket).

Except this, these changes are LGTM.

2022-10-25 23:55 UTC, hong6316 approved these changes
OK :)

2022-10-31 06:29 UTC, MikyungKim commented on moonstone/all-samples/src/components/SampleItem/SampleItem.js
> +import {useCallback} from "react";
```suggestion
import {useCallback} from 'react';
```

2022-10-31 06:30 UTC, MikyungKim commented on sandstone/all-samples/src/App/App.js
> +import {StaticRouter} from "react-router-dom/server";
```suggestion
import {StaticRouter} from 'react-router-dom/server';
```

2022-10-31 06:31 UTC, MikyungKim commented on sandstone/tutorial-hello-enact/package.json
> +    "@enact/ui": "4.5.2",
Why is this version pinned?

2022-10-31 06:32 UTC, MikyungKim commented on ui/all-samples/src/App/App.js
>  import Scroller from '@enact/ui/Scroller';
Please reorder imports.

2022-10-31 06:35 UTC, MikyungKim requested changes
Please find my comments.

2022-10-31 06:35 UTC, MikyungKim commented on agate/all-samples/src/App/App.js
> +import {StaticRouter} from "react-router-dom/server";
```suggestion
import {StaticRouter} from 'react-router-dom/server';
```

2022-10-31 06:35 UTC, MikyungKim commented on moonstone/all-samples/src/App/App.js
> +import {StaticRouter} from "react-router-dom/server";
```suggestion
import {StaticRouter} from 'react-router-dom/server';
```

2022-10-31 09:53 UTC, andreitirlalge commented on sandstone/tutorial-hello-enact/package.json
> +    "@enact/ui": "4.5.2",
to be honest, i did not notice it, but it was here for a while. Thank you for noticing. I will correct it

2022-10-31 11:27 UTC, daniel-stoian-lgp commented on agate/all-samples/src/App/App.js
> +	functional: true,
```suggestion

	functional: true,
```

2022-10-31 11:27 UTC, daniel-stoian-lgp commented on moonstone/all-samples/src/App/App.js
> +	functional: true,
```suggestion

	functional: true,
```

2022-10-31 11:27 UTC, daniel-stoian-lgp commented on sandstone/all-samples/src/App/App.js
> +	functional: true,
```suggestion

	functional: true,
```

2022-10-31 11:27 UTC, daniel-stoian-lgp commented on ui/all-samples/src/App/App.js
> +	functional: true,
```suggestion

	functional: true,
```

2022-10-31 11:29 UTC, daniel-stoian-lgp reviewed
added missing empty lines

2022-10-31 11:58 UTC, daniel-stoian-lgp approved these changes

2022-11-01 00:50 UTC, MikyungKim reviewed
Just out of curiousity, is the image showing well in your PC for all-samples > PatternSinglePanel?
I'm not sure but my result showing a gray image.
![image](https://user-images.githubusercontent.com/5037429/199135418-8f742081-350f-48d3-a5ac-f72239869263.png)
🤔

2022-11-01 08:13 UTC, daniel-stoian-lgp commented
> Just out of curiousity, is the image showing well in your PC for all-samples > PatternSinglePanel? I'm not sure but my result showing a gray image. ![image](https://user-images.githubusercontent.com/5037429/199135418-8f742081-350f-48d3-a5ac-f72239869263.png) 🤔

Images in All-samples sample fot all theme libraries never loaded on our PCs. We did an analysis and it is trying to load them from a  path inside all-samples folder, but they are located in the other samples' folder. 
One solution could be to duplicate those images or check how to do configure routing for this specific case, but in another user story :) What do you think?

2022-11-02 02:58 UTC, MikyungKim commented
🤔 I was confused since the built one uploaded to our server shows images well. Let's take a look at this in another ticket.

2022-11-02 03:01 UTC, MikyungKim commented on agate/all-samples/package.json
> +    "@enact/agate": "^2.0.1",
Oh, we recently updated agate to 2.0.2.

2022-11-03 02:37 UTC, MikyungKim approved these changes
LGTM

2022-11-03 02:39 UTC, merged