WRP-4194: Apply correct lint option to samples
enactjs/samples pull request #192
Opened 2022-12-14 09:00 UTC by andreitirlalge

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Some samples did not have the correct eslint configuration.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Applied the correct lint option to samples and fixed eslint warnings that occured after this change.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
Due to some changes made in the configuration of the eslint, new warnings occured that were fixed in this PR as well.
(e.g ImportSkins.js, utils.js, SamplePage.js, Content.js)

### Links
[//]: # (Related issues, references)
WRP-4194

### Comments
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com

2022-12-14 13:21 UTC, daniel-stoian-lgp commented on sandstone/custom-skin/src/components/ImportSkin/ImportSkin.js
> +								console.log(err);	//eslint-disable-line
/* eslint-disable no-console */   at the beggining of the file

2022-12-14 13:21 UTC, daniel-stoian-lgp commented on sandstone/pattern-react18-new/src/views/Suspense/SamplePage.js
> +const renderItem = ({index, ...rest}) => {	//eslint-disable-line
Please actually solve the eslint warning. there's no point in suppressing it

renderItem.propTypes = {
	index: PropTypes.number,
};

2022-12-14 13:21 UTC, daniel-stoian-lgp commented on sandstone/custom-skin/src/utils.js
> +		console.log(err);	//eslint-disable-line
/* eslint-disable no-console */   at the beggining of the file

2022-12-14 13:21 UTC, daniel-stoian-lgp commented on sandstone/pattern-react18-new/src/views/UseTransition/Content.js
> +function Content ({page}) {		//eslint-disable-line
Please actually solve the eslint warning. There's no point in suppressing it

2022-12-14 16:16 UTC, daniel-stoian-lgp approved these changes

2022-12-15 00:44 UTC, seunghoh requested changes
Please use the PR template even in the samples Repo. 
I see some other code fixes beyond the lint option. Then you should mention it in the PR description for the code reviewer.
CC: @daniel-stoian-lgp

2022-12-15 08:08 UTC, andreitirlalge commented
I've added a PR template and changed the description.
CC: @seunghoh

2022-12-15 10:34 UTC, seunghoh approved these changes

2022-12-20 08:11 UTC, hong6316 commented
to @andreitirlalge 

1. Item "Resolution" is empty.
Please fill out the appropriate content.
(I think it's okay to copy the contents of "Issue Resolved/Feature Added")

2. When checking PR, some changes are different from the main purpose of this PR (e.g. Import Skin.js, utils.js, etc.).
Please write these changes in "Additional Considers".

2022-12-22 00:56 UTC, hong6316 approved these changes
LGTM

2022-12-22 00:57 UTC, merged