WRQ-5674: Support to change video resolution on video player
enactjs/samples pull request #218
Opened 2024-01-22 08:53 UTC by mmyelyn

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [ ] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
This feature was created by a request to be able to video resolution change in our video player. 
So We've created guidelines to help support this functionality.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Add video resolution change support using hls.js to the pattern-video-player-custom sample

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRQ-5674

### Comments
Enact-DCO-1.0-Signed-off-by: Hyelyn Kim ([myelyn.kim@lge.com](mailto:sc.baek@lge.com))

2024-01-22 08:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/enactjs/samples?pullRequest=218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/enactjs/samples?pullRequest=218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/enactjs/samples?pullRequest=218) it.</sub>

2024-02-07 09:00 UTC, juwonjeong commented
Please update README.md file

2024-02-13 06:50 UTC, juwonjeong commented on package.json
> +
It seems that an unnecessary line is added. Please check it.

2024-02-13 06:50 UTC, juwonjeong commented on sandstone/pattern-video-player-custom/README.md
> +Functionally, you can change the resolution of the video in m3u8 video.
I think it would be better to update the descriptions as mentioned above. 
```suggestion
Functionally, you can change the resolution of the `m3u8` video.
```

2024-02-13 06:50 UTC, juwonjeong commented on sandstone/pattern-video-player-custom/src/App/App.js
> +							{resolutions.map((resolution, index) => {
Please check the console warning.

2024-02-20 07:07 UTC, mmyelyn commented on sandstone/pattern-video-player-custom/src/App/App.js
> +							{resolutions.map((resolution, index) => {
I added key prop. I want to key value as `resolution.id` but this value was received always 0. So I used `resolution._attrs[0].RESOLUTION`. Alternatively, although it is not recommended, I can also use an index.

2024-02-20 07:07 UTC, mmyelyn commented on sandstone/pattern-video-player-custom/README.md
> +Functionally, you can change the resolution of the video in m3u8 video.
Updated

2024-02-20 07:14 UTC, mmyelyn commented on package.json
> +
Removed

2024-03-04 06:13 UTC, juwonjeong commented on sandstone/pattern-video-player-custom/package.json
> +}
Please revert this change

2024-03-04 07:21 UTC, mmyelyn commented
A conflict occurred because the README content previously included in develop was missing. Since it is correct that the README content is being updated, i have added it again in the PR.

2024-03-04 08:43 UTC, juwonjeong commented
> A conflict occurred because the README content previously included in develop was missing. (Merged into develop in #222, but reverted in #221) Since it is correct that the README content is being updated, I have added it again in the PR.

Okay, I also added a change that was dropped.

2024-03-05 01:11 UTC, juwonjeong approved these changes
LGTM

2024-03-07 07:06 UTC, seunghoh requested changes
Please merge the README and js files when https://github.com/enactjs/samples/pull/219 merged.

2024-03-18 06:00 UTC, seunghoh requested changes
1. The resolution selection panel stays open and wait , the video control is hidden. what happens then? 
2. I don't know which resolution we selected.
3. How can I go to the default? (no selection and automation)

2024-03-19 08:50 UTC, mmyelyn commented
> 1. The resolution selection panel stays open and wait , the video control is hidden. what happens then?
> 2. I don't know which resolution we selected.
> 3. How can I go to the default? (no selection and automation)

1. Thank you. Instead of using overlay, I changed the implementation to dropdown.
2. This was resolved with a change to the dropdown. You can see the selected resolution.
3. Added default value 'auto'. If not selected, the default value is set to auto.

2024-03-19 09:06 UTC, seunghoh requested changes
Dropdown doesn't keep the value that I've selected. 
For example, select the resolution 640*480 -> close the panel -> open the panel again but dropdown selects Auto.

2024-03-19 10:01 UTC, mmyelyn commented
> Dropdown doesn't keep the value that I've selected. For example, select the resolution 640*480 -> close the panel -> open the panel again but dropdown selects Auto.

I found an edge case. When I selected the first item in the dropdown, I checked that the index was 0, so it became a falsy value. Fixed this.

2024-03-20 06:27 UTC, seunghoh approved these changes

2024-03-20 06:42 UTC, merged

2024-03-20 06:46 UTC, seunghoh commented
Merged, but I slightly updated your PR. @mmyelyn