WRQ-5673: Added subtitle to a sample video player app
enactjs/samples pull request #219
Opened 2024-01-31 08:02 UTC by vJIYEv

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
https://github.com/enactjs/enact/issues/3188
Following this issue, we consider to support subtitle for video player if we can.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
I made a subtitle button in a sample video player app.

- Clicking the subtitle button shows subtitlePanel
- A subtitle can be selected in subtitlePanel
- If a subtitle is selected, imported subtitle file is added into video as a track tag.
- If a subtitle is not selected, track is disabled.
- If video and subtitle file change, previous track is disabled and new track is added.  

.srt file, which is required to support in the issue, is not supported because it is not supported in W3C standard.
.vtt file (WebVTT) can be added instead. 

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRQ-5673

### Comments
Enact-DCO-1.0-Signed-off-by: Jiye Kim (jiye.kim@lge.com)

2024-02-13 08:53 UTC, juwonjeong commented
Please update PR title and PR description

2024-02-13 08:57 UTC, juwonjeong commented
Please resolve the conflict

2024-02-13 08:57 UTC, juwonjeong commented on sandstone/pattern-video-player-custom/src/App/App.js
> +	const handleSubtitle = useCallback(() => setSubtitleVisible(!subtitleVisible), [subtitleVisible]);
```suggestion
	const handleSubtitle = useCallback(() => setSubtitleVisible(prevSubtitleVisible => !prevSubtitleVisible), []);
```

2024-02-13 08:57 UTC, juwonjeong commented on sandstone/pattern-video-player-custom/src/App/videos.js
> +import subtitlefile from './subtitle.vtt';  // import subtitle file
```suggestion
import subtitleFile from './subtitle.vtt';  // import subtitle file
```

2024-02-14 08:28 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/src/App/videos.js
> +import subtitlefile from './subtitle.vtt';  // import subtitle file
I accepted your suggestion.

2024-02-14 08:28 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/src/App/App.js
> +	const handleSubtitle = useCallback(() => setSubtitleVisible(!subtitleVisible), [subtitleVisible]);
I accepted your suggestion.

2024-02-15 08:48 UTC, juwonjeong commented on sandstone/pattern-video-player-custom/src/App/App.js
> +	}, [subtitle, subtitleVisible]);
Please check in the inspector that it has multiple <track> elements after toggling the sub button.
If it is true, I think it should be fixed.

As I'm not familiar with video track handling, You don't have to fix as same as my suggestion. 
```suggestion
	useEffect(() => {
		const video = videoRef.current.getVideoNode().media;
		let trackElement = document.getElementById('track');
		if (subtitle) {
			if (!document.getElementById('track')) {
				trackElement = document.createElement('track');
				trackElement.id = "track";
				video.appendChild(trackElement);
			}
			trackElement.src = subtitle;
			trackElement.kind = "subtitles";
		} else {
			video.textTracks[0].mode = "disabled";
		}
	}, [subtitle]);
```
Also, handleSubtitle need to be fixed together.
```
const handleSubtitle = useCallback(() => {
		const video = videoRef.current.getVideoNode().media;
		if (video.textTracks[0]) {
			video.textTracks[0].mode = subtitleVisible ? "disabled" : "showing"
		}
			setSubtitleVisible(!subtitleVisible)
		}, [subtitleVisible]
	);
```

2024-02-15 08:48 UTC, juwonjeong commented on sandstone/pattern-video-player-custom/README.md
> +WebVTT format (.vtt files) subtitles are supported only, and other formats should be converted into WebVTT format.
```suggestion

In [App.js](src/App/App.js), the application handles WebVTT format(.vtt files) subtitles for display in VideoPlayer.
Only WebVTT format (.vtt files) subtitles are supported, and other formats should be converted into WebVTT format.
```

2024-02-15 08:48 UTC, juwonjeong commented on sandstone/pattern-video-player-custom/README.md
>  The video data, including the URL and mime type, are stored in [videos.js](src/App/videos.js). For `m3u8` videos, the mime type should be `application/x-mpegURL`.
```suggestion
The video data, including the URL, mime type, and subtitle are stored in [videos.js](src/App/videos.js). For `m3u8` videos, the mime type should be `application/x-mpegURL`.

```

2024-02-16 02:25 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/README.md
>  The video data, including the URL and mime type, are stored in [videos.js](src/App/videos.js). For `m3u8` videos, the mime type should be `application/x-mpegURL`.
I accepted your suggestion.

2024-02-16 02:25 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/README.md
> +WebVTT format (.vtt files) subtitles are supported only, and other formats should be converted into WebVTT format.
I accepted your suggestion.

2024-02-16 02:27 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/src/App/App.js
> +	}, [subtitle, subtitleVisible]);
This code has a problem: previous subtitle remains after change the video.
So I changed code. Please check committed code.

2024-02-19 07:28 UTC, juwonjeong approved these changes
LGTM

2024-02-29 05:58 UTC, seunghoh requested changes
Looks nonsense to have English and Korean in a single vtt file. Please separate in 2 files and make the option to select subtitle language.

2024-02-29 05:58 UTC, seunghoh commented on sandstone/pattern-video-player-custom/src/App/App.js
> +			track.kind = "subtitles";
You missed mandatory `srclang`. Please read carefully the doc https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#srclang

2024-02-29 05:58 UTC, seunghoh commented on sandstone/pattern-video-player-custom/src/App/subtitle.vtt
> +테스트입니다.
자막 테스트입니다.

2024-02-29 05:58 UTC, seunghoh commented on sandstone/pattern-video-player-custom/src/App/subtitle.vtt
> +This is for test.
This is a subtitle test.

2024-02-29 05:58 UTC, seunghoh commented on sandstone/pattern-video-player-custom/README.md
> +Only WebVTT format (.vtt files) subtitles are supported, and other formats should be converted into WebVTT format.
Additionally, this application supports subtitles in the WebVTT format (.vtt files). These subtitles can be displayed in the VideoPlayer. Please note that only subtitles in the WebVTT format are supported.

2024-03-04 07:49 UTC, juwonjeong commented
Please resolve conflicts in README.md carefully as mentioned in https://github.com/enactjs/samples/pull/218#issuecomment-1975881863.

2024-03-07 07:07 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/src/App/App.js
> +			track.kind = "subtitles";
I added `srclang` to track element.

2024-03-07 07:07 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/src/App/subtitle.vtt
> +테스트입니다.
I changed the text.

2024-03-07 07:07 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/src/App/subtitle.vtt
> +This is for test.
I changed the text.

2024-03-07 07:31 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/README.md
> +Only WebVTT format (.vtt files) subtitles are supported, and other formats should be converted into WebVTT format.
I rewrited the sentence about WebVTT format
and included the sentence from https://github.com/enactjs/samples/pull/218

2024-03-07 09:01 UTC, seunghoh requested changes
We don't use a Capital for the lang file. capital is only for the region like ko-KR, en-US

2024-03-07 09:01 UTC, seunghoh commented on sandstone/pattern-video-player-custom/src/App/App.js
> +			<MainPanel
It should be `VideoSelectionPanel` since you've added one more panel. above

2024-03-07 09:01 UTC, seunghoh commented on sandstone/pattern-video-player-custom/src/App/App.js
> +			<SubtitlePanel
`SubtitleSelectionPanel`

2024-03-07 09:03 UTC, seunghoh commented on sandstone/pattern-video-player-custom/README.md
> +Only WebVTT format (.vtt files) subtitles are supported, and other formats should be converted into WebVTT format.
Please make the exactly same MD as I suggested above

2024-03-07 09:45 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/src/App/App.js
> +			<MainPanel
I changed the panel name to `VideoSelectionPanel`

2024-03-07 09:45 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/src/App/App.js
> +			<SubtitlePanel
I changed the panel name to `SubtitleSelectionPanel`

2024-03-08 00:28 UTC, seunghoh requested changes
Fix prop `videoIndex` bleeding.
Please also reply why there's a force-push in your commit

2024-03-08 09:10 UTC, vJIYEv commented on sandstone/pattern-video-player-custom/README.md
> +Only WebVTT format (.vtt files) subtitles are supported, and other formats should be converted into WebVTT format.
I changed MD file following your suggestion.

2024-03-08 09:29 UTC, vJIYEv commented
I reverted force-push and fixed prop bleeding.

2024-03-11 08:56 UTC, seunghoh approved these changes

2024-03-11 09:14 UTC, seunghoh commented
Good work!

2024-03-11 09:15 UTC, merged