WRQ-9365: Added VirtualGridList sample to load data incrementally for infinite scrolling
enactjs/samples pull request #225
Opened 2024-03-14 09:46 UTC by mmyelyn

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
I have a request on how virtualgridlist should be implemented if data is continuously loaded.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
I used VirtualGridList's onScrollStop handler to load data when the scroll reaches the bottom.
Assuming that data has been fetched, I implemented it to attach mock data.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRQ-9365

### Comments
Enact-DCO-1.0-Signed-off-by: Hyelyn Kim ([myelyn.kim@lge.com](mailto:sc.baek@lge.com))

2024-07-25 08:35 UTC, juwonjeong commented
Please check the enact lint --strict in this sample

2024-07-25 08:44 UTC, juwonjeong commented on sandstone/pattern-virtualgridlist-infinite-scroll/resources/ilibmanifest.json
> +}
Please add a new line

2024-07-25 08:44 UTC, juwonjeong commented on sandstone/pattern-virtualgridlist-infinite-scroll/src/App/package.json
> +}
please add a new line

2024-07-25 08:44 UTC, juwonjeong commented on sandstone/pattern-virtualgridlist-infinite-scroll/src/views/MainView.js
> +const defaultSize = 10;
I think defaultSize needs to be fixed because in FHD or 4k dimensions, scroll does not appear.

2024-07-25 08:44 UTC, juwonjeong commented on sandstone/pattern-virtualgridlist-infinite-scroll/src/views/MainView.js
> +		</Panel>
Please fix the indentation

2024-07-25 08:44 UTC, juwonjeong commented on sandstone/pattern-virtualgridlist-infinite-scroll/README.md
> +In this app, load data when scrolling reaches the bottom of the virtualgridlist. Use your API server to data fetch to load the data.
```suggestion
In this app, data is loaded when scrolling reaches the bottom of the virtualgridlist. Use your API server to fetch data to load.
```

2024-07-25 08:44 UTC, juwonjeong commented on sandstone/pattern-virtualgridlist-infinite-scroll/README.md
> +Performance may decrease when using the onScroll handler, so use the onScrollStop handler like in the sample.
```suggestion
Performance may decrease when using the `onScroll` handler, so use the `onScrollStop` handler like in the sample.

```

2024-07-25 09:22 UTC, juwonjeong commented
Could you please add this pattern sample link to all-samples as other samples?
https://github.com/enactjs/samples/blob/master/sandstone/all-samples/src/App/App.js

2024-07-31 04:15 UTC, mmyelyn commented on sandstone/pattern-virtualgridlist-infinite-scroll/src/views/MainView.js
> +const defaultSize = 10;
Fixed defaultSize to 30 to cover resolutions for all screenTypes. The added data size was kept at 10 for ease of testing.

2024-08-01 06:13 UTC, juwonjeong approved these changes
LGTM

2024-08-02 06:40 UTC, seunghoh commented on sandstone/pattern-virtualgridlist-infinite-scroll/src/views/MainView.js
> +const addedListSize = 10;
Let's use defaultSize to 50 and addedListSIze to 30 to see scroll position changing more obviously.

2024-08-02 06:40 UTC, seunghoh commented on sandstone/pattern-virtualgridlist-infinite-scroll/src/reportWebVitals.js
> +export default reportWebVitals;
We don't use WebVitals on samples.

2024-08-02 06:40 UTC, seunghoh commented on sandstone/pattern-virtualgridlist-infinite-scroll/src/index.js
> +import reportWebVitals from './reportWebVitals';
We don't use WebVitals on this samples repo.

2024-08-02 06:40 UTC, seunghoh commented on sandstone/all-samples/src/App/App.js
> +import {App as PatternVirtualgridlistInfiniteScroll} from '../../../pattern-virtualgridlist-infinite-scroll/src/App/App';
Let's use `pattern-virtualgridlist-incremental-load`. `infinite-scroll` is not the main topic on this sample. 
Please change the folder name as well.

2024-08-02 06:40 UTC, seunghoh commented on sandstone/pattern-virtualgridlist-infinite-scroll/README.md
> +This project was bootstrapped with the Enact [cli](https://github.com/enactjs/cli).
```suggestion
## Incremental Data Loading in VirtualGridList Pattern

A sample Enact application that demonstrates how to load items incrementally in a VirtualGridList.

Run `npm install` then `npm run serve` to have the app running on [http://localhost:8080](http://localhost:8080), where you can view it in your browser.

#### Enact Components Used
- `sandstone/ImageItem`
- `sandstone/Panels/Header`
- `sandstone/Panels/Panel`
- `sandstone/VirtualList/VirtualGridList`

In this app, data is loaded as you scroll to the bottom of the VirtualGridList. Use your API server to fetch data to load.
Performance may decrease when using the `onScroll` handler, so use the `onScrollStop` handler as shown in the sample.

---

This project was bootstrapped with the Enact [cli](https://github.com/enactjs/cli).
```

2024-08-02 06:43 UTC, seunghoh requested changes
Let's change the sample name.

2024-08-02 10:29 UTC, mmyelyn commented on sandstone/all-samples/src/App/App.js
> +import {App as PatternVirtualgridlistInfiniteScroll} from '../../../pattern-virtualgridlist-infinite-scroll/src/App/App';
That's a good point. It's changed. I also modified the sample's title.

2024-08-02 10:30 UTC, mmyelyn commented
> Let's change the sample name.

The sample name and other reviews have all been applied.

2024-08-05 05:26 UTC, seunghoh approved these changes

2024-08-05 05:26 UTC, merged