WRQ-25355: A video player sample playing google video ads
enactjs/samples pull request #236
Opened 2024-07-16 08:58 UTC by vJIYEv

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
https://github.com/enactjs/enact/issues/3245
Following this issue, I made a Sandstone VideoPlayer sample playing Google Video Ads.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

According to google adsense help, IMA SDK is needed to play google ads in a custom video player.
(Guidelines: https://support.google.com/adsense/answer/6391192?hl=en&ref_topic=1706004&sjid=6550346971434809951-AP)
So I integrated IMA SDK in a sample app, following the tutorial.
(Tutorial: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side)

And I adjusted some details to make it work with sandstone video player.
 - `adContainer` node is placed in front of the `VideoPlayer` component to toggle the media controller by clicking the video layer.
 - `playPauseButton` is disabled before initializing IMA and during playing the ad.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRQ-25355

### Comments
Enact-DCO-1.0-Signed-off-by: Jiye Kim (jiye.kim@lge.com)

2024-07-26 04:34 UTC, juwonjeong commented on sandstone/pattern-video-player-google-ads/src/App/App.js
> +	const [adsManager, setAdsManager] = useState(null);
It seems that adsManager needs to be declare with ref. 
As of now, it looks like adsManger is null in the onAddError handler, for example.

2024-08-01 01:37 UTC, juwonjeong commented on sandstone/pattern-video-player-google-ads/src/App/App.js
> +			adsRequest.adTagUrl = 'https://pubads.g.doubleclick.net/gampad/ads?' +
Where did you get this adTagUrl? Is it okay to use this url?

2024-08-01 01:37 UTC, juwonjeong commented on sandstone/pattern-video-player-google-ads/README.md
> +A sample Enact application that demonstrates how to play simple Google Video Ads with Sandstone VideoPlayer.
```suggestion
A sample Enact application that demonstrates how to play Google Video Ads with Sandstone VideoPlayer.

```

2024-08-01 01:37 UTC, juwonjeong commented on sandstone/pattern-video-player-google-ads/README.md
> +This is a simple example to show how to integrate IMA SDK into a sandstone video player app, following [IMA SDK tutorial](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-si
```suggestion
This is a simple example to show how to integrate IMA SDK into a sandstone video player app, following the [IMA SDK tutorial](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side). Please refer the tutorial page about basic IMA SDK features.

```

2024-08-01 01:37 UTC, juwonjeong commented on sandstone/pattern-video-player-google-ads/README.md
> +In this sample, some details are different with the original tutorial.
```suggestion
In this sample, some details are different from the original tutorial.

```

2024-08-06 09:41 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/src/App/App.js
> +			adsRequest.adTagUrl = 'https://pubads.g.doubleclick.net/gampad/ads?' +
This vast url is from IMA documentation: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags
They provide sample urls for test.

2024-08-06 09:52 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/README.md
> +In this sample, some details are different with the original tutorial.
ok

2024-08-06 09:52 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/README.md
> +This is a simple example to show how to integrate IMA SDK into a sandstone video player app, following [IMA SDK tutorial](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-si
ok

2024-08-06 09:52 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/README.md
> +A sample Enact application that demonstrates how to play simple Google Video Ads with Sandstone VideoPlayer.
ok

2024-08-06 09:53 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/src/App/App.js
> +	const [adsManager, setAdsManager] = useState(null);
I changed to declare adsManager with ref.
and also changed adDisplayContainer.

2024-08-07 06:39 UTC, juwonjeong commented on sandstone/pattern-video-player-google-ads/src/App/App.js
>  	}, [adsRef, adsManager]);
Do we still need adsManager in this dependencyArray? Please check if we need adsRef and adsManager in here. Also check other dependency arrays.

2024-08-08 07:46 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/src/App/App.js
>  	}, [adsRef, adsManager]);
I removed unnecessary dependencies.
They were needed when I added wrong event handlers before.
But now they are not needed.

2024-08-09 00:21 UTC, juwonjeong approved these changes
LGTM

2024-08-14 05:16 UTC, seunghoh requested changes
1. Please add an inline comment to App.js explaining what the app developer needs to do to add Ads. This is intended to replace a separate guide document.
2. Please remove these errors on devtools when run the application
- imasdk.googleapis.com/js/core/bridge3.658.1_en.html#goog_271167832:1 The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. 
- Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

2024-08-14 05:16 UTC, seunghoh commented on sandstone/pattern-video-player-google-ads/src/App/App.js
> +			adsRequest.adTagUrl = 'https://pubads.g.doubleclick.net/gampad/ads?' +
If so, please explicitly add the source of the url as a comment.

2024-08-14 05:16 UTC, seunghoh commented on sandstone/pattern-video-player-google-ads/webos-meta/appinfo.json
> +  "vendor": "LGE-SVL",
Why do we need a `webos-meta` in the samples repo? 
CC: @juwonjeong

2024-08-14 05:16 UTC, seunghoh commented on sandstone/pattern-video-player-google-ads/README.md
> +A sample Enact application that demonstrates how to play Google Video Ads with Sandstone VideoPlayer.
```suggestion
A sample Enact application that demonstrates how to integrate Google Video Ads with Sandstone VideoPlayer.
```

2024-08-14 05:16 UTC, seunghoh commented on sandstone/pattern-video-player-google-ads/README.md
> +If you want to add Google Video Ads into your custom video player, you should integrate IMA3 HTML5 SDK. ([HTML5 video advertising guidelines](https://support.google.com/adsense/answer/6391192?hl=en&r
```suggestion
To add Google Video Ads to your custom video player, you need to integrate the IMA3 HTML5 SDK. Refer to the [HTML5 video advertising guidelines](https://support.google.com/adsense/answer/6391192?hl=en&ref_topic=1706004&sjid=6550346971434809951-AP) for more information.
```

2024-08-14 05:16 UTC, seunghoh commented on sandstone/pattern-video-player-google-ads/README.md
> +This is a simple example to show how to integrate IMA SDK into a sandstone video player app, following the [IMA SDK tutorial](https://developers.google.com/interactive-media-ads/docs/sdks/html5/clien
```suggestion
This example demonstrates how to integrate the IMA SDK into a Sandstone video player app, following the [IMA SDK tutorial](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side). Please refer to the tutorial page for basic IMA SDK features.
```

2024-08-14 05:16 UTC, seunghoh commented on sandstone/pattern-video-player-google-ads/README.md
> +And `playPauseButton` is disabled before initializing IMA and during playing the ad.
```suggestion
In this sample, some details differ from the original tutorial:
- The `adContainer` node is placed in front of the `VideoPlayer` component to toggle the media controller by clicking the video layer.
- The `playPauseButton` is disabled before initializing IMA and during ad playback.
```

2024-08-14 05:16 UTC, seunghoh commented on sandstone/pattern-video-player-google-ads/README.md
> +You can find a more detailed view inside of [App.js](src/App/App.js)
```suggestion
For a more detailed view, check inside [App.js](src/App/App.js).
```

2024-08-20 10:33 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/README.md
> +A sample Enact application that demonstrates how to play Google Video Ads with Sandstone VideoPlayer.
ok

2024-08-20 10:34 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/README.md
> +If you want to add Google Video Ads into your custom video player, you should integrate IMA3 HTML5 SDK. ([HTML5 video advertising guidelines](https://support.google.com/adsense/answer/6391192?hl=en&r
ok

2024-08-20 10:34 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/README.md
> +This is a simple example to show how to integrate IMA SDK into a sandstone video player app, following the [IMA SDK tutorial](https://developers.google.com/interactive-media-ads/docs/sdks/html5/clien
ok

2024-08-20 10:34 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/README.md
> +And `playPauseButton` is disabled before initializing IMA and during playing the ad.
ok

2024-08-20 10:34 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/README.md
> +You can find a more detailed view inside of [App.js](src/App/App.js)
ok

2024-08-23 02:17 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/webos-meta/appinfo.json
> +  "vendor": "LGE-SVL",
I added `webos-meta` like other samples.
and I changed vendor from `LGE-SVL` to `LGE`.

2024-08-23 02:28 UTC, vJIYEv commented
1. Added guide comments to App.js.
2. For errors on devtools when run the application,
- `imasdk.googleapis.com/js/core/bridge3.658.1_en.html#goog_271167832:1 The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol.`
  - This error only appears on a `http` (untrustworthy) page, not a `https` page. As the log says, ads should be requested on a `https` page.
- `Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`
  - I couldn't find this error log.

2024-09-06 05:48 UTC, seunghoh requested changes
Please check my comment and the app doens't work now without any console error. Please check

2024-09-06 05:48 UTC, seunghoh commented on sandstone/pattern-video-player-google-ads/src/App/App.js
> +import {MediaControls} from '@enact/sandstone/MediaPlayer';
Let's add the overall guide of this file at the top of this App.js

2024-09-06 05:48 UTC, seunghoh commented on sandstone/pattern-video-player-google-ads/src/App/App.js
> +			adsRequest.adTagUrl = 'https://pubads.g.doubleclick.net/gampad/ads?' +
Rather than put the sample url, please add a guide comment that you can copy and paste ad tag ULRs from the https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags

2024-09-10 02:03 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/src/App/App.js
> +			adsRequest.adTagUrl = 'https://pubads.g.doubleclick.net/gampad/ads?' +
Instead, I added the source of the URL and explanations

2024-09-10 02:05 UTC, vJIYEv commented on sandstone/pattern-video-player-google-ads/src/App/App.js
> +import {MediaControls} from '@enact/sandstone/MediaPlayer';
I added comments about the sample at the top of the file.

2024-09-10 07:20 UTC, seunghoh approved these changes

2024-09-10 07:22 UTC, seunghoh commented
LGTM but I switch to Draft PR because it doesn't fit the purpose of the Enact sample.

2024-09-26 08:42 UTC, closed without merging